config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/work', to: 'pages#work'
  get '/welcome', to: 'pages#welcome'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  root 'pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def welcome
 end
 def work
 end
 def about
 end
 def contact
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body><ul class="nav">
  <li class="nav-item">
    <%= link_to "Home", welcome_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "View My Work", work_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Visit my website", 'https://www.sergeikofman.ca/concert-works', class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "About", about_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Contact", contact_path, class: "nav-link" %>
  </li>
</ul>
<footer class="footer">
<div class="social_buttons">
 <a href="https://github.com/sergeikofman-dealmaker"><img src="https://cdn-icons-png.flaticon.com/128/3291/3291695.png" style="width:20px;height:20px;"></a>
 <a href="https://www.linkedin.com/in/sergei-kofman-ba63a8103/"><img src="https://cdn-icons-png.flaticon.com/128/1384/1384014.png" style="width:20px;height:20px;"></a>
 <a href="https://www.instagram.com/measure.music/"><img src="https://cdn-icons-png.flaticon.com/128/1384/1384031.png" style="width:20px;height:20px;"></a>
 </div>
 <br>
 <br>
 <div>
 <p style="text-align:center">Copyright Sergei Kofman 2024</p>
 </div>
</footer>
    <%= yield %>
  </body>

</html>

app/views/pages/about.html.erb
<div class="container">
<img src="https://i.imgur.com/GHEWLus.jpg" alt="spotify cover" style="width:100%;">
<p>
Sergei Kofman (b. 1996) is an imaginative young composer based in Toronto. Sergei  completed his masters degree in Composition at the University of Toronto in 2020, where he was awarded the 2021 Ann H. Atkinson prize for an outstanding electroacoustic work, for his piece Voices in the Whir. in 2022, Sergei received support from the Toronto Arts Council for his project I Hear the Scent of Change and Stillness, an EP combining acoustic instruments, organic textures, and synthesized and industrial sounds. The project was released in 2023 and was accompanied by a concert at Toronto's ArrayMusic. He is active as a composer, producer, audio engineer, pianist, and educator. 

Sergei writes music for various media as well as the concert hall. He draws on an eclectic combination of influences in his work. His music has been performed by ensembles around Canada and the United States.</p>
</div>

app/views/pages/contact.html.erb
<div class="container">
 <p>this is the contact page</p>
 <p>find some of my contact links below</p>
 <ul>
  <li>Email: sergeilevkofman@gmail.com</li>
  <li>GitHub: https://github.com/sergei-kofman</li>
  <li>Instagram: https://www.instagram.com/measure.music/</li>
  <li>LinkedIn: https://www.linkedin.com/in/sergei-kofman-ba63a8103/</li>
 </ul>
</div>

app/views/pages/welcome.html.erb
<div class="container"
<p>this is the welcome page</p>
<%= link_to "Click here to see some of my work", work_path %>
</div>

app/views/pages/work.html.erb
<div class="container"> <!-- main section -->
 <div class="row">
  <img src="https://i.imgur.com/rmFz0Zn.png" alt="popular films project" style="width:100%;">
 </div>
 <p>this is some of my work</p>
 <div class="row">
  <div class="col-lg-4">
   <img src="https://i.imgur.com/SUeQEvJ.png" alt="bass music project" style="width:100%;">
  </div>
  <div class="col-lg-4">
   <img src="https://i.imgur.com/SUeQEvJ.png" alt="bass music project" style="width:100%;">
  </div>
  <div class="col-lg-4">
   <img src="https://i.imgur.com/SUeQEvJ.png" alt="bass music project" style="width:100%;">
  </div>
 </div>
</div>